/** See PfeifferPumpCommands for decriptions. */

#include "config.h"
#include "SerialComms.h"
#include "ArduinoPfeiffer.h"
#include <Arduino.h>

void turnOnPump(ArduinoPfeiffer pfeiffer_pump, RS485Device& pump_serial_wrapper);

void turnOffPump(ArduinoPfeiffer pfeiffer_pump, RS485Device& pump_serial_wrapper);

pressure_measurement readPressure(ArduinoPfeiffer pfeiffer_gauge, RS485Device& gauge_serial_wrapper);

void setPumpSpeed(ArduinoPfeiffer pfeiffer_pump, RS485Device& pump_serial_wrapper, float percent);

void send_command(ASCII_char command, RS485Device& serial, ArduinoPfeiffer& device);

void send_and_process(ASCII_char command, RS485Device& serial, ArduinoPfeiffer& device);

// --------------------------------------------------------
// WARNING - THE FOLLOWING PARAMETERS WERE UNAPOLOGETICALLY
// GENERATED BY PERPLEXITY AND HAVE NOT BEEN VERIFIED
// --------------------------------------------------------

// ----------------------------
// Core parameters
// ----------------------------
#define PUMP_POWER_PARAM          "010"  // Pumping station ON/OFF (backing + turbo)
#define PUMP_OPMODE_PARAM         "026"  // Speed setting mode (enable % speed control)
#define PUMP_SPEED_SET_PARAM      "707"  // Speed setpoint in % of nominal
#define PUMP_SPEED_HZ_SET_PARAM   "308"  // Set rotation speed (Hz) readback
#define PUMP_SPEED_HZ_ACT_PARAM   "309"  // Actual rotation speed (Hz)
#define PUMP_SPEED_RPM_SET_PARAM  "397"  // Set rotation speed (rpm) readback
#define PUMP_SPEED_RPM_ACT_PARAM  "398"  // Actual rotation speed (rpm)
#define PUMP_PRESSURE_PARAM       "740"  // Pressure value (ActiveLine) // TODO: check
#define PUMP_GAUGETYPE_PARAM      "738"  // Type of pressure gauge
#define PUMP_ERROR_CODE_PARAM     "303"  // Error / status code string
#define PUMP_STATUS_PARAM         "302"  // Speed switchpoint reached / status bits

// ----------------------------
// Boolean / mode values (old bool: 6 chars)
// ----------------------------
#define PVAL_BOOL_FALSE           "000000"
#define PVAL_BOOL_TRUE            "111111"

// Pumping station ON/OFF
#define PUMP_OFF_VALUE            PVAL_BOOL_FALSE  // P:010 = 000000
#define PUMP_ON_VALUE             PVAL_BOOL_TRUE   // P:010 = 111111

// Speed setting mode (P:026, u_short_int 0/1, but often used like bool)
#define SPEED_MODE_DISABLED_VALUE "000"  // treat as 0
#define SPEED_MODE_ENABLED_VALUE  "001"  // treat as 1 (enable speed control) // TODO: check

// ----------------------------
// Integer / percent helpers (6-char fixed format as strings)
// (you can generate these in code instead of hardcoding)
// ----------------------------

// Example common speed setpoints for P:707 (u_real, % * 100)
#define SPEED_20_PERCENT          "002000"  // 20.00 %
#define SPEED_50_PERCENT          "005000"  // 50.00 %
#define SPEED_75_PERCENT          "007500"  // 75.00 %
#define SPEED_100_PERCENT         "010000"  // 100.00 %

// ----------------------------
// Gas mode (P:027) – u_short_int (3 digits)
// ----------------------------
#define GAS_MODE_PARAM            "027"    // Gas mode selection
#define GAS_MODE_HEAVY            "000"    // >39 amu (e.g. Ar)
#define GAS_MODE_LIGHT            "001"    // ≤39 amu
#define GAS_MODE_HELIUM           "002"    // He

// ----------------------------
// RS485 / control interface
// ----------------------------
#define IFACE_CTRL_MODE_PARAM     "060"    // Interface / remote control source
#define IFACE_LOCK_PARAM          "061"    // Lock interface selection
#define RS485_ADDRESS_PARAM       "797"    // RS-485 device address (1–255)
#define NOMINAL_SPEED_PARAM       "777"    // Nominal speed confirmation (Hz)

// Common values for P:060 (data type u_short_int, 3 chars; macros as strings)
#define IFACE_MODE_REMOTE         "001"    // Remote/X3 digital input priority
#define IFACE_MODE_RS485          "002"    // RS-485 / serial control priority

// ----------------------------
// Venting / accessories (if you use them)
// ----------------------------
#define VENT_ENABLE_PARAM         "012"    // Venting enabled/disabled
#define VENT_MODE_PARAM           "030"    // Venting mode (delayed / none / direct)
#define CFG_ACCESSORY_B1_PARAM    "036"    // Config accessory connection B1
#define CFG_RELAY1_PARAM          "045"    // Configuration Relay 1
#define CFG_RELAY2_PARAM          "046"    // Configuration Relay 2
#define SEALING_GAS_PARAM         "050"    // Sealing gas ON/OFF

// Example accessory/relay config values (3‑digit u_short_int strings)
#define RELAY_CFG_ROT_SPEED_SW    "000"    // Rotation speed switchpoint attained
#define RELAY_CFG_NO_ERROR        "001"
#define RELAY_CFG_ERROR           "002"
#define RELAY_CFG_WARNING         "003"
#define RELAY_CFG_ERR_OR_WARN     "004"
#define RELAY_CFG_SET_SPEED_OK    "005"
#define RELAY_CFG_PUMP_ON         "006"
#define RELAY_CFG_PUMP_ACCEL      "007"
#define RELAY_CFG_PUMP_DECEL      "008"
#define RELAY_CFG_CONST_ZERO      "009"
#define RELAY_CFG_CONST_ONE       "010"
#define RELAY_CFG_REMOTE_ACTIVE   "011"
#define RELAY_CFG_HEATING         "012"
#define RELAY_CFG_BACKING_PUMP    "013"
#define RELAY_CFG_SEALING_GAS     "014"
#define RELAY_CFG_PUMPING_STATION "015"

// ----------------------------
// Analog output configuration (if needed)
// ----------------------------
#define CFG_AO1_PARAM             "055"    // Analog output AO1 config
#define AO1_ROTATION_SPEED        "000"    // 0–10 V = 0–100% f_nominal
#define AO1_POWER                 "001"
#define AO1_CURRENT               "002"
#define AO1_CONST_ZERO            "003"
#define AO1_CONST_TEN_V           "004"
#define AO1_FOLLOWS_AI1           "005"

// ----------------------------
// Pressure / gauge related
// ----------------------------
#define PRESSURE_PARAM            "340"    // Pressure (ActiveLine)
#define CTR_NAME_PARAM            "350"    // Controller name
#define CTR_SOFTWARE_PARAM        "351"    // Controller software version
#define GAUGE_TYPE_PARAM          "738"    // Type of pressure gauge

// ----------------------------
// Misc status / info
// ----------------------------
#define DRIVE_POWER_PARAM         "316"    // Drive power (W)
#define DRIVE_CURRENT_PARAM       "310"    // Drive current (A)
#define OPERATING_HOURS_PARAM     "311"    // Operating hours
